configuracion_index:
    path:     /
    defaults: { _controller: "AnexaCooperadoraBundle:Configuracion:index" }
    methods:  GET

configuracion_show:
    path:     /{id}/show
    defaults: { _controller: "AnexaCooperadoraBundle:Configuracion:show" }
    methods:  GET

configuracion_new:
    path:     /new
    defaults: { _controller: "AnexaCooperadoraBundle:Configuracion:new" }
    methods:  [GET, POST]

configuracion_edit:
    path:     /{id}/edit
    defaults: { _controller: "AnexaCooperadoraBundle:Configuracion:edit" }
    methods:  [GET, POST]

configuracion_delete:
    path:     /{id}/delete
    defaults: { _controller: "AnexaCooperadoraBundle:Configuracion:delete" }
    methods:  DELETE
