inicio:
    path:     /
    defaults: { _controller: AnexaCooperadoraBundle:Index:index }

login:
    path:     /login
    defaults: { _controller: AnexaCooperadoraBundle:Index:login }

sendMail:
    path:     /sendMail
    defaults: { _controller: AnexaCooperadoraBundle:Index:sendMail }
