usuario_index:
    path:     /
    defaults: { _controller: "AnexaCooperadoraBundle:User:index" }
    methods:  GET

usuario_show:
    path:     /{id}/show
    defaults: { _controller: "AnexaCooperadoraBundle:User:show" }
    methods:  GET

usuario_new:
    path:     /new
    defaults: { _controller: "AnexaCooperadoraBundle:User:new" }
    methods:  [GET, POST]

usuario_edit:
    path:     /{id}/edit
    defaults: { _controller: "AnexaCooperadoraBundle:User:edit" }
    methods:  [GET, POST]

usuario_delete:
    path:     /{id}/delete
    defaults: { _controller: "AnexaCooperadoraBundle:User:delete" }
    methods:  [GET, POST]

usuario_estado:
    path:     /{id}/toogle
    defaults: { _controller: "AnexaCooperadoraBundle:User:estado" }
    methods:  [GET, POST]
