base: "http://localhost/sistemaAnexa/web/app.php/"
resource: "http://localhost/sistemaAnexa/web"
index:
	controller: "index"
	action: "index"
	role: notRegistered

login:
	controller: "index"
	action: "login"
	role: notRegistered
sendMail:
	controller: "index"
	action: "sendMail"
	role: notRegistered

backend:
	controller: "usuario"
	action: "login"
	role: notRegistered

backend/index:
	controller: "backend"
	action: "index"
	role: isRemember


backend/salir:
	controller: "usuario"
	action: "logout"
	role: notRegistered

backend/alumno:
 	controller: "alumno"
 	action: "index"
 	role: isRemember

backend/alumno/agregar:
 	controller: "alumno"
 	action: "create"
 	role: rolAdmin

backend/alumno/editar:
 	controller: "alumno"
 	action: "update"
 	role: rolAdmin

backend/alumno/eliminar:
 	controller: "alumno"
 	action: "delete"
 	role: rolAdmin

backend/alumno/ver:
 	controller: "alumno"
 	action: "view"
 	role: rolConsulta

backend/responsable:
 	controller: "responsable"
 	action: "index"
 	role: rolAdmin

backend/responsable/agregar:
 	controller: "responsable"
 	action: "create"
 	role: rolAdmin

backend/responsable/editar:
 	controller: "responsable"
 	action: "update"
 	role: rolAdmin

backend/responsable/eliminar:
 	controller: "responsable"
 	action: "delete"
 	role: rolAdmin

backend/responsable/ver:
 	controller: "responsable"
 	action: "view"
 	role: rolAdmin

backend/usuario:
 	controller: "usuario"
 	action: "index"
 	role: rolAdmin

backend/usuario/agregar:
 	controller: "usuario"
 	action: "create"
 	role: rolAdmin

backend/usuario/editar:
 	controller: "usuario"
 	action: "update"
 	role: rolAdmin

backend/usuario/eliminar:
 	controller: "usuario"
 	action: "delete"
 	role: rolAdmin

backend/usuario/estado:
 	controller: "usuario"
 	action: "toogle"
 	role: rolAdmin

backend/usuario/ver:
 	controller: "usuario"
 	action: "view"
 	role: rolAdmin


backend/configuracion:
 	controller: "configuracion"
 	action: "index"
 	role: rolAdmin

backend/configuracion/editar:
 	controller: "configuracion"
 	action: "update"
 	role: rolAdmin

backend/cuota:
	controller: "cuota"
	action: "index"
	role: rolGestion

backend/cuota/agregar:
 	controller: "cuota"
 	action: "create"
 	role: rolGestion

backend/cuota/editar:
 	controller: "cuota"
 	action: "update"
 	role: rolGestion

backend/cuota/eliminar:
 	controller: "cuota"
 	action: "delete"
 	role: rolGestion

backend/pago:
	controller: "pago"
	action: "index"
	role: rolGestion

backend/pago/seleccionado:
	controller: "pago"
	action: "pagoSeleccionado"
	role: rolGestion

backend/pago/total:
	controller: "pago"
	action: "pagoTotal"
	role: rolGestion

backend/pago/editar:
	controller: "pago"
	action:	"update"
	role: rolGestion

backend/pago/eliminar:
	controller: "pago"
	action: "delete"
	role: rolGestion

backend/pago/listarPagos:
	controller: "pago"
	action: "verPagos"
	role: rolGestion

backend/recorrido:
	controller: "recorrido"
	action: "index"
	role: rolAdmin

backend/estadisticas:
	controller: "estadistica"
	action: "index"
	role: rolGestion

backend/estadistica/graficos:
	controller: "estadistica"
	action: "graficar"
	role: rolGestion

backend/estadistica/graficoPDF:
	controller: "estadistica"
	action: "graficarPdf"
	role: rolGestion

backend/listado:
	controller: "listado"
	action: "index"
	role: rolConsulta

backend/listado/matriculados:
	controller: "listado"
	action: "matriculaPaga"
	role: rolConsulta

backend/listado/matriculadosPDF:
	controller: "listado"
	action: "matriculasPagasPdf"
	role: rolConsulta

backend/listado/cuotasPagas:
	controller: "listado"
	action: "cuotasPagas"
	role: rolConsulta

backend/listado/cuotasPagasPDF:
	controller: "listado"
	action: "cuotasPagasPdf"
	role: rolConsulta

backend/listado/cuotasImpagas:
	controller: "listado"
	action: "cuotasImpagas"
	role: rolConsulta

backend/listado/cuotasImpagasPDF:
	controller: "listado"
	action: "cuotasImpagasPdf"
	role: rolConsulta

backend/listado/comisionCobrada:
	controller: "listado"
	action: "comisionCobrada"
	role: rolGestion

backend/listado/comisionCobradaPDF:
	controller: "listado"
	action: "comisionCobradaPdf"
	role: rolGestion
