listado_index:
    path:     /
    defaults: { _controller: "AnexaCooperadoraBundle:Listado:index" }
    methods:  GET

listado_matriculados:
    path:     /matriculasPagas
    defaults: { _controller: "AnexaCooperadoraBundle:Listado:matriculados" }
    methods:  POST

listado_pago_becado:
    path:     /cuotasPagasyBecadas
    defaults: { _controller: "AnexaCooperadoraBundle:Listado:cuotasPagas" }
    methods:  POST

listado_cuotas_impagas:
    path:     /cuotasNoPagas
    defaults: { _controller: "AnexaCooperadoraBundle:Listado:cuotasNoPagas" }
    methods:  POST


