anexa_cooperadora_backend:
    path:     /backend
    defaults: { _controller: AnexaCooperadoraBundle:Backend:index }

anexa_cooperadora_inicio:
    prefix:     /
    resource: "@AnexaCooperadoraBundle/Resources/config/routing/inicio.yml"

anexa_cooperadora_alumno:
    prefix:     /backend/alumno
    resource: "@AnexaCooperadoraBundle/Resources/config/routing/alumno.yml"

anexa_cooperadora_couta:
    prefix:     /backend/cuota
    resource: "@AnexaCooperadoraBundle/Resources/config/routing/cuota.yml"

anexa_cooperadora_pago:
    prefix:     /backend/pago
    resource: "@AnexaCooperadoraBundle/Resources/config/routing/pago.yml"

anexa_cooperadora_listado:
    prefix:     /backend/listado
    resource: "@AnexaCooperadoraBundle/Resources/config/routing/listado.yml"

anexa_cooperadora_configuracion:
    prefix:     /backend/configuracion
    resource: "@AnexaCooperadoraBundle/Resources/config/routing/configuracion.yml"

anexa_cooperadora_usuario:
    prefix:     /backend/usuario
    resource: "@AnexaCooperadoraBundle/Resources/config/routing/user.yml"

anexa_cooperadora_tipoCobrador:
    prefix:     /backend/tipoCobrador
    resource: "@AnexaCooperadoraBundle/Resources/config/routing/tipoCobrador.yml"

login_check:
    path: /login_check

logout:
    path: /logout

login:
    path: /entrar
    defaults: { _controller: AnexaCooperadoraBundle:User:login }

fos_login:
    path: /login

register:
    path: /register/
    defaults: { _controller: AnexaCooperadoraBundle:User:new }

paginacion:
    path: /paginacion
    defaults: { _controller: AnexaCooperadoraBundle:Configuracion:paginacion }

